# Paths
DATASET_PATH = "./datasets/"
MODEL_PATH = "./models/"

# Constant variables
PLAYER1 = 1.0
PLAYER2 = 2.0

# Hyper-parameters
THINKING_TIME_AGENT1 = 0.1
THINKING_TIME_AGENT2 = 0.1
N_TIME_STEP = 2

# TicTacToe
GAME_NAME = "TicTacToe"
N_ROW = 3
N_COL = 3
N_LEVELS = 1

# Bashni
#GAME_NAME = "Bashni"
#N_ROW = 8
#N_COL = 8
#N_LEVELS = 10
#MAX_SAMPLE = NUM_TRIALS * N_ROW * N_COL * N_LEVELS + 1

# Trial parameters
NUM_TRIALS = 50
MAX_SAMPLE = NUM_TRIALS * N_ROW * N_COL * N_LEVELS + 1	

# NN parameters
N_EPOCHS = 50
BATCH_SIZE = 10
VERBOSE = True
VALIDATION_SPLIT = 0.2
FILTERS = 30 # 75
KERNEL_SIZE = (2,2) # (4,4)
N_RES_LAYER = 10
LEARNING_RATE = 1e-2
MOMENTUM = 0.9
REG_CONST = 1e-5
