# Paths
DATASET_PATH = "./datasets/"
MODEL_PATH = "./models/"

# Constant variables
PLAYER1 = 1.0
PLAYER2 = 2.0

# Hyper-parameters
THINKING_TIME_AGENT1 = 0.1
THINKING_TIME_AGENT2 = 0.1
N_TIME_STEP = 2

# TicTacToe
#GAME_NAME = "TicTacToe"
#N_ROW = 3
#N_COL = 3
#N_LEVELS = 1
#MAX_GAME_DURATION = 10

# Bashni
GAME_NAME = "Bashni"
N_ROW = 8
N_COL = 8
N_LEVELS = 24
MAX_GAME_DURATION = 30

# Trial parameters
NUM_TRIALS = 10
MAX_SAMPLE = NUM_TRIALS * N_ROW * N_COL * N_LEVELS + 1	

# NN parameters
RANDOM_SEED = 42
N_EPOCHS = 5
BATCH_SIZE = 128
VERBOSE = True
VALIDATION_SPLIT = 0.2
FILTERS = 128
KERNEL_SIZE = (3,3)
FIRST_KERNEL_SIZE = (5,5) 
N_RES_LAYER = 10
NEURONS_VALUE_HEAD = 128
OPTIMIZER = "adam"
LEARNING_RATE = 1e-3
MOMENTUM = 0.9
REG_CONST = 1e-4
